# Generated by Django 3.0.7 on 2021-01-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210105_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
